### ISSUE TITLE
Support changing the hotkey

### ISSUE THREAD

**Issue by xdy** [digitalpacman/foundryvtt-pf2e-reach-templates#1]
This would be useful for those who already use the R key for something else. Like, say, me. :)
Probably best done by adding support for https://github.com/flamewave000/dragonflagon-fvtt/tree/master/lib-df-hotkeys that way it also plays nicely with other modules that use it to handle keybinding.

**Comment by digitalpacman** [comment]
Accepted. I'll see if I can't knock that out

**Comment by digitalpacman** [comment]
@xdy added functionality in version 1.0.1

you can now choose a hotkey between a-z. i did not end up using the dragon flagon library
